---
apiVersion: v1
kind: Service
metadata:
  name: <name>-service
spec:
  selector:
    app: <name>
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 8080
  #type: LoadBalancer # work only for aws 
