name: hello-deploy
on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - dev

env:
  SERVICE: HelloWorld
  DOTNET_VERSION: '6.0.401'
jobs:
  Build_zip:
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: ./.github/workflows/build
      with:
        service: ${{ env.SERVICE }}
        dotnet_version: ${{ env.DOTNET_VERSION }}
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.SERVICE }}
        path: ./services/${{  env.SERVICE }}/bin/${{  env.SERVICE }}.zip
  BuildContainers:
      runs-on: ubuntu-latest
      # if: ${{ github.event_name == 'pull_request' }}
      steps:
        - uses: actions/checkout@v3
        - name: Download zip from
          uses: actions/download-artifact@v3
          with:
            name: ${{ env.SERVICE }} 
        - shell: pwsh
          run: | 
            Expand-Archive./services/${{  env.SERVICE }}/bin/${{ env.SERVICE }}.zip  -DestinationPath ./
            Get-ChildItem
            docker build -t ${{ env.SERVICE }}:latest .

      