name: hello-deploy
on:
  workflow_dispatch:
  push:
    branches:
    - test

env:
  SERVICE: HelloWorld
  DOTNET_VERSION: '6.0.401'
  IMAGE_NAME: helloworld
jobs:
  Build_zip:
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: ./.github/workflows/build
      with:
        service: ${{ env.SERVICE }}
        dotnet_version: ${{ env.DOTNET_VERSION }}
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build.zip
  BuildContainers:
      runs-on: ubuntu-latest
      needs: build_zip
      # if: ${{ github.event_name == 'pull_request' }}
      steps:
        - uses: actions/checkout@v3
        - name: Download zip from
          uses: actions/download-artifact@v3
          with:
            name: build
        - name: create docker images
          shell: pwsh
          run: |
            $outputDirectory = Get-Location
            $source_folder="source"
            $source_path="$outputDirectory\$source_folder"
            $build_folder="build"
            $build_path="$outputDirectory\$build_path"
            New-Item -Path "$outputDirectory" -Name "$source_folder" -ItemType Directory
            New-Item -Path "$outputDirectory" -Name "$build_folder" -ItemType Directory

            Expand-Archive "$outputDirectory\build.zip" -DestinationPath $source_path
           
            $files = Get-ChildItem "$source_path"
            foreach ($f in $files){
                 $service_name=$f.Name 
                 $image_name=$service_name.ToLower()
                 Write-Host docker build --build-arg "APP_NAME=$service_name" --build-arg "BUILD_PATH=$source_folder" -t "$image_name`:latest" .
                 docker build --build-arg "APP_NAME=$service_name" --build-arg "BUILD_PATH=$source_folder" -t "$image_name`:latest" .
                 New-Item -Path "$build_path" -Name "$service_name" -ItemType Directory
                 docker save -o "$build_path\$service_name\$image_name-latest.tar" "$image_name`:latest"
            }

        - shell: bash
          run: | 
            docker images
     