name: test
on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - test
env:
  DOTNET_VERSION: '6.0.401'
jobs:
  build_zip:
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: perent workflow call 
      uses: ./.github/workflows/build
      with:
        dotnet_version: ${{ env.DOTNET_VERSION }}
