name: test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create docker images
        shell: pwsh
        run: |
           docker pull httpd
           docker save httpd |  gzip > httpd.tar.gz
      - name: save final artifact
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: httpd.tar.gz